<?php

namespace Chigi\Component\IO;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-04 at 02:06:49.
 */
class FileTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var File
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        FileSystem::getFileSystem()->setCharset("gbk");
        //$this->object = new File("TEST");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Chigi\Component\IO\File::getName
     * @todo   Implement testGetName().
     */
    public function testGetName() {
        $file = new File("test");
        $this->assertEquals(FileSystem::getFileSystem()->normalize(\getcwd() . "/test"), $file->getAbsolutePath(), "mock the filename `test`");
    }

    /**
     * @covers Chigi\Component\IO\File::getAbsolutePath
     * @todo   Implement testGetAbsolutePath().
     */
    public function testGetAbsolutePath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Chigi\Component\IO\File::length
     * @todo   Implement testLength().
     */
    public function testLength() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Chigi\Component\IO\File::exists
     * @todo   Implement testExists().
     */
    public function testExists() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Chigi\Component\IO\File::isFile
     * @todo   Implement testIsFile().
     */
    public function testIsFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
