<?php

namespace Chigi\Component\IO;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-04 at 02:58:19.
 */
class FileSystemTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var FileSystem
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new FileSystem;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Chigi\Component\IO\FileSystem::getFileSystem
     * @todo   Implement testGetFileSystem().
     */
    public function testGetFileSystem() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Chigi\Component\IO\FileSystem::setCharset
     * @todo   Implement testSetCharset().
     */
    public function testSetCharset() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Chigi\Component\IO\FileSystem::getSeparator
     * @todo   Implement testGetSeparator().
     */
    public function testGetSeparator() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Chigi\Component\IO\FileSystem::getPathSeparator
     * @todo   Implement testGetPathSeparator().
     */
    public function testGetPathSeparator() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Chigi\Component\IO\FileSystem::normalize
     * @todo   Implement testNormalize().
     */
    public function testNormalize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Chigi\Component\IO\FileSystem::resolve
     * @todo   Implement testResolve().
     */
    public function testResolve() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Chigi\Component\IO\FileSystem::exists
     * @todo   Implement testExists().
     */
    public function testExists() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Chigi\Component\IO\FileSystem::isFile
     * @todo   Implement testIsFile().
     */
    public function testIsFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Chigi\Component\IO\FileSystem::localFileName
     * @todo   Implement testLocalFileName().
     */
    public function testLocalFileName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
